### ISSUE TITLE
file upload does not respect bearer authentication

### ISSUE THREAD

**Issue by jlines** [z0mt3c/hapi-swaggered#26]
I am using hapi-swaggered/hapi-swaggered-ui tools.

hapi-swaggered-ui is configured to use a bearer token in api calls via the following config

'hapi-swaggered-ui':{ authorization: { // see above
            field: 'Authorization',
            scope: 'header', // header works as well
            valuePrefix: 'Bearer '// prefix incase
        } },

This works great for most calls except file upload calls, which is configured using the method found in the hapi-swaggered documentation for file uploads. In the case of file uploads the configured auth is not sent and no bearer token field is used.

**Comment by z0mt3c** [comment]
Thanks for reporting! Seems to be a bug in swagger-ui/swagger-js... Reported here: swagger-api/swagger-js#407

**Comment by z0mt3c** [comment]
Now here: swagger-api/swagger-ui#1249

**Comment by z0mt3c** [comment]
fixed since hapi-swaggered-ui@1.5.0 (swagger-ui@2.1.0)
