### ISSUE TITLE
really long model names

### ISSUE THREAD

**Issue by Gregy** [z0mt3c/hapi-swaggered#29]
Hi,
I am trying out this plugin but I have problem right from the start. The generated model names are so long, they push model information off screen.

![image](https://cloud.githubusercontent.com/assets/342731/7615111/8a0765ec-f99b-11e4-89ad-954182048e04.png)

Is there some way to influence the name? Seems to me that better name generating scheme for payload might be 'payload'+path+httpMethod. I can have documents with a lot of fields and the names are, as you can see, quite crazy :)

Thank you for the plugin. Seems nice :)

**Comment by z0mt3c** [comment]
Sure,  just customize the model name by adding a meta attribute:

```js
Joi.object({...}).meta({className:'NewName'})
```

**Comment by Gregy** [comment]
I read the readme again. It is there alright. I am really sorry, I should have slept more :(

Thank you!
