### ISSUE TITLE
Swagger-UI error when not using localhost

### ISSUE THREAD

**Issue by delaneyj** [z0mt3c/hapi-swaggered#33]
Everything works great when viewing with http://localhost/docs.

If I change to host ip, 127.0.0.1, or server.info.host I get an `Error {...} ` button on the `/docs/index.html' page after the routes.  When I click on it get something like `[{"level":"error","message":"Can't read from file http://127.0.0.1:8000/swagger/swagger"}]` however if I set the page directly to that url it resolves fine.

Is there something wrong with my initial config?

**Comment by z0mt3c** [comment]
I will have a look into... but i guess it's a CORS issue so may just try to add ```cors: true``` to the plugin options for now.

**Comment by delaneyj** [comment]
Setting `cors:true` doesn't to seem to have an effect in my environment.

**Comment by z0mt3c** [comment]
ahhh sorry - i didn't get the point ;-) You are referring to this:

![bildschirmfoto 2015-06-01 um 17 13 06](https://cloud.githubusercontent.com/assets/1782471/7916009/89b85336-0881-11e5-8936-ca4b851fac89.png)

This is the swagger schema validator which is automatically disabled for "localhost" because it uses a remote service for validation and your swagger schema (hosted on localhost) cannot be fetched from remote. I thought setting swaggerOptions.validationUrl to null should disable it completely but unfortunately it does not. "false" actually does the job but is not accepted by the validation schema. I will fix it with the next release of hapi-swaggered-ui.

Follow up here: z0mt3c/hapi-swaggered-ui#8

**Comment by delaneyj** [comment]
Great thank you for the quick response!

**Comment by DavidBiesack** [comment]
Where does one set swaggerOptions.validationUrl  ? I can't find it mentioned in any source files or on https://github.com/swagger-api/swagger-ui README

**Comment by DavidBiesack** [comment]
I found this https://github.com/swagger-api/swagger-ui/issues/630 
which says where to set it but unfortunately points to a source location
https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L33
that is not tied to a commit, so the line has moved/changed 

using query parameter as per
https://github.com/swagger-api/swagger-ui#parameters 
is also a poor solution (and also does not seem to work)

**Comment by onenetwork** [comment]
Using `validatorUrl` instead of `validationUrl` solved this problem for me.  I'm on tag 2.1.3.

      window.swaggerUi = new SwaggerUi({
        url: url,
        validatorUrl: undefined,

**Comment by boloindia** [comment]
Aah!!! I was using 127.0.0.1 and had to modify the condition in swagger-ui.js as:
if ('validatorUrl' in opts.swaggerOptions) {
      // Validator URL specified explicitly
      this.model.validatorUrl = opts.swaggerOptions.validatorUrl;
    } else if (this.model.url.indexOf('localhost') > 0 || **this.model.url.indexOf('127.0.0.1')>0**) {
      // Localhost override
      this.model.validatorUrl = null;
    } else {
      // Default validator
      if(window.location.protocol === 'https') {
        this.model.validatorUrl = 'https://online.swagger.io/validator';
      }
      else {
        this.model.validatorUrl = 'http://online.swagger.io/validator';
      }
    }

**Comment by jsandeepm** [comment]
Hi boloindia,

may I know what exactly you changed in swagger-ui.js?

thanks

**Comment by codestellar** [comment]
@jsandeepm Since I was using 127.0.0.1 only so I modified the else if condition the bold part
else if (this.model.url.indexOf('localhost') > 0 || **this.model.url.indexOf('127.0.0.1')>0) **

**Comment by vjpulivarthi** [comment]
I followed codestellar , added the else part which was not in my swagger-ui.js. It was able to read Json file in Chrome but not in IE. Any suggestions?

**Comment by laguiz** [comment]
I was able to disable the validation by adding `&validatorUrl=` in the url. I give an empty url and NO http call is made. I'm using swagger-ui version `3.0.19`. 

Working for me : `http://localhost:9000/assets/lib/swagger-ui/index.html?url=/assets/swagger/v1.yaml&validatorUrl=`

Not that this way no http call is made to try the validation. 

I previously tried things like `&validatorUrl=null` or `&validatorUrl=undefined` but an http call was made failing of course (note that with current version of swagger-ui parse query strings as `string` and a work in progress is looking to parse as `json`).

**Comment by buddike1112** [comment]
@laguiz you can disable validator like below (thought to share, may be it can help any one)

 .**EnableSwaggerUi**(c => {
                 c.**DisableValidator**();
              }

**Comment by rennyallen** [comment]
Setting `validatorUrl` to false or null solved this problem for me:
```js
    const ui = SwaggerUIBundle({
    url: "/api/v1/doc/swagger",
    validatorUrl: false,
    // other code here...
    })
```
