### ISSUE TITLE
date/datetime not showing up in model

### ISSUE THREAD

**Issue by delaneyj** [z0mt3c/hapi-swaggered#34]
[the 2.0 spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) supports date/datetime, but if you use ```Joi.date().required()``` in a payload nothing seems work.  

Any thoughts?

**Comment by z0mt3c** [comment]
Its a bug - It should be supported out-of-the-box. But you can help yourself by specifying the swaggerType and format yourself according to the [swagger specifications](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types)...

Joi.date().required().meta({swaggerType: 'string', format: 'date-time'})

**Comment by delaneyj** [comment]
Thanks!
