### ISSUE TITLE
Joi.object().max(10) causing invalid rendering of swagger

### ISSUE THREAD

**Issue by delaneyj** [z0mt3c/hapi-swaggered#38]
Using validation like this
```
body:{
  foo: Joi.object().max(10)
}
```

causing hapi-swagger to give an error like this
```
500 : {"success":false,"error":{"type":"InternalServerError","description":"child \"definitions\" fails because [child \"FooModel\" fails because [child \"properties\" fails because [child \"foo\" fails because [\"maximum\" is not allowed, \"&#x24;ref\" is not allowed]]]]","details":"General http error, would be a 500 normally."}} http://localhost:8000/swagger/swagger
``` 
with no other rendering on the page except the header.

[Joi's documentation](https://github.com/hapijs/joi#objectmaxlimit) says limiting object keys in this fashion is supported.  Any thoughts?

**Comment by z0mt3c** [comment]
Was a bug - but i guess people don't hit it often ;-) Need a release?

**Comment by delaneyj** [comment]
When its convenient, it was used in a reply so not technically blocking anything for us right now.  Would really like some thoughts on (https://github.com/z0mt3c/hapi-swaggered/issues/35) before a release.

**Comment by delaneyj** [comment]
Same issue on `.description('foo')`
