### ISSUE TITLE
9.0.x Support?

### ISSUE THREAD

**Issue by Icehunter** [z0mt3c/hapi-swaggered#40]
Hi! I was just wondering if there will be support for 9.X as I'd like to upgrade my system but it crashes because of issues around caching and changes in hapi.

**Comment by some-say** [comment]
+1

**Comment by z0mt3c** [comment]
Yes of course - just didn't have time yet to look into it ;-)

**Comment by z0mt3c** [comment]
Just had a look - no big deal... hapi9 branches are up and working... just need to update docs before release.

**Comment by z0mt3c** [comment]
hapi-swagger@2.3.0 and hapi-swagger-ui@2.0.0
