### ISSUE TITLE
Be more lenient with versions

### ISSUE THREAD

**Issue by mwawrusch** [z0mt3c/hapi-swaggered#50]
Right now hapi-swaggered requires a < 11.0 hapi dependency, which means we cannot run it with 11.0 (but it most likely will work). I get why you put it in there, but I think for convenience' sake it would be good to just specify a lower bound. People version their production systems explicitly anyways, so if a hapi update breaks swaggered it's not a big deal.

BTW, really great module.

**Comment by nackjicholson** [comment]
:+1: I'm getting peerDependency errors as well trying to use hapi@11.0.0

**Comment by mwawrusch** [comment]
Thx, appreciate it.
