### ISSUE TITLE
Hapi v11.x Support

### ISSUE THREAD

**Issue by dhm116** [z0mt3c/hapi-swaggered#54]
Please update to work with Hapi v11.x. Changelog is located at https://github.com/hapijs/hapi/issues/2850

**Comment by jplock** [comment]
This would be great!

**Comment by z0mt3c** [comment]
Are you missing any new features? Whats lacking? Will have a look next week.

**Comment by dhm116** [comment]
Hrm....I thought due to the way the peer dependencies are defined, it was not possible to use this with Hapi v11.x, but I'm thinking it was possibly a different issue. I can double-check tomorrow and follow up.

**Comment by z0mt3c** [comment]
yeah this has been fixed with #50 (since 2.4.1)

**Comment by dhm116** [comment]
Sorry, we had 2.4.0 installed and I didn't notice that 2.4.1 addressed the dependencies. Closing!
