### ISSUE TITLE
Incorrect properties generated for strings with max, min, etc.

### ISSUE THREAD

**Issue by object88** [z0mt3c/hapi-swaggered#61]
When processing a Joi schema which uses [max](https://github.com/hapijs/joi/blob/master/API.md#stringmaxlimit-encoding) or min to represent the allowable string length, hapi-swaggered generates max & min in the resulting JSON swagger document, rather than [maxLength](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) and minLength.  This is handled in lib/utils.js, I think in the parseBaseModelAttributes function.

I'm a little short on time, but I will try to show a specific example later.

**Comment by object88** [comment]
I don't have a specific example, but I forked the project and added the feature myself.  Once I figure out how to push my changes back up to my own fork, I will issue a pull request, perhaps?

**Comment by z0mt3c** [comment]
Yes sure... didnt have time to look into yet but pull requests are welcome! of course :-)

**Comment by object88** [comment]
Great!  I issued [a request](https://github.com/z0mt3c/hapi-swaggered/pull/62).
