### ISSUE TITLE
Please check the example for 'File upload (Hapi 8)

### ISSUE THREAD

**Issue by Tatort79** [z0mt3c/hapi-swaggered#8]
Any additional field (like name) is not send to the server.

Version: swagger_2_specs
Commit: ae0cdf43fce8a26b564cac63d241af15f84a7da1

**Comment by z0mt3c** [comment]
Swagger-u bug... swagger-api/swagger-ui#944

**Comment by z0mt3c** [comment]
Fixed - increased swagger-ui version to 2.1.8-M1.
Released as 1.2.2.
